//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnexC
    {
        public int IdAnnexC { get; set; }
        public int IdProgramCycle { get; set; }
        public string Author { get; set; }
        public System.DateTime DateRegister { get; set; }
        public string Project { get; set; }
        public int IdPriority { get; set; }
        public int IdStrategy { get; set; }
        public int IdFocusRightsGroup { get; set; }
        public int IdMSRPRightsGroup { get; set; }
        public int IdFocusObjective { get; set; }
        public int IdMSRPObjective { get; set; }
        public int IdFocusImpactIndicatorOutput { get; set; }
        public int IdMSRPOutput { get; set; }
        public string ProjectTitle { get; set; }
        public string SubAgreement { get; set; }
        public int IdImplementerCode { get; set; }
        public int IdImplementationMechanism { get; set; }
        public int IdOfficeRisponsible { get; set; }
        public int IdSite { get; set; }
        public int IdCostCentre { get; set; }
        public int IdProjectLocationDepartament { get; set; }
        public int IdProjectLocationMunicipality { get; set; }
        public int IdProjectLocationSubMunicipality { get; set; }
        public int ProjectLocationComunityName { get; set; }
        public int IdUNIT { get; set; }
        public int IdCurrency { get; set; }
        public decimal Budget { get; set; }
        public string USD { get; set; }
        public string Donor { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ParameterDetail ParameterDetail2 { get; set; }
        public virtual ParameterDetail ParameterDetail3 { get; set; }
        public virtual ParameterDetail ParameterDetail4 { get; set; }
        public virtual ParameterDetail ParameterDetail5 { get; set; }
        public virtual ParameterDetail ParameterDetail6 { get; set; }
        public virtual ParameterDetail ParameterDetail7 { get; set; }
        public virtual ParameterDetail ParameterDetail8 { get; set; }
        public virtual ParameterDetail ParameterDetail9 { get; set; }
        public virtual ParameterDetail ParameterDetail10 { get; set; }
        public virtual ParameterDetail ParameterDetail11 { get; set; }
        public virtual ParameterDetail ParameterDetail12 { get; set; }
        public virtual ParameterDetail ParameterDetail13 { get; set; }
        public virtual ParameterDetail ParameterDetail14 { get; set; }
        public virtual ParameterDetail ParameterDetail15 { get; set; }
        public virtual ParameterDetail ParameterDetail16 { get; set; }
        public virtual ParameterDetail ParameterDetail17 { get; set; }
    }
}
