//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public int IdAttachment { get; set; }
        public int IdComponentByModule { get; set; }
        public int IdInformation { get; set; }
        public string AttachmentName { get; set; }
        public string Description { get; set; }
        public int IdAttachmentType { get; set; }
        public int IdAttachmentCondition { get; set; }
        public byte[] Attachment { get; set; }
    
        public virtual ComponentsByModule ComponentsByModule { get; set; }
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    }
}
