//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int IdAudit { get; set; }
        public int IdUser { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public byte[] EntityBefore { get; set; }
        public byte[] EntityAfter { get; set; }
        public int IdKeyEntity { get; set; }
        public string IdKeyConsult { get; set; }
        public string IPAdress { get; set; }
        public int IdProcessEntity { get; set; }
        public string Operation { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
