//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentsByModule
    {
        public ComponentsByModule()
        {
            this.SessionComponentsByModule = new HashSet<SessionComponentsByModule>();
            this.Attachments = new HashSet<Attachments>();
        }
    
        public int IdComponentByModule { get; set; }
        public string Name { get; set; }
        public int IdModule { get; set; }
        public string Description { get; set; }
    
        public virtual Modules Modules { get; set; }
        public virtual ICollection<SessionComponentsByModule> SessionComponentsByModule { get; set; }
        public virtual ICollection<Attachments> Attachments { get; set; }
    }
}
