//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostApproval
    {
        public int IdCostApproval { get; set; }
        public int IdItineraryInformation { get; set; }
        public int IdCertifyingOffice { get; set; }
        public int IdTitle { get; set; }
        public string AssignedAccount { get; set; }
        public string Account { get; set; }
        public string VoucherNumber { get; set; }
        public double Value { get; set; }
        public int IdCanceled { get; set; }
        public int IdLegalization { get; set; }
        public int RegisterAdded { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ParameterDetail ParameterDetail2 { get; set; }
        public virtual ParameterDetail ParameterDetail3 { get; set; }
        public virtual ItineraryInformation ItineraryInformation { get; set; }
    }
}
