//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataProject
    {
        public DataProject()
        {
            this.NationalPriorities = new HashSet<NationalPriorities>();
        }
    
        public int IdDataProject { get; set; }
        public string ProjectTitle { get; set; }
        public int IdProjectlocationDepartament { get; set; }
        public int IdProjectlocationMunicipality { get; set; }
        public int IdProjectlocationSubMunicipality { get; set; }
        public string ImplementationPartners { get; set; }
        public decimal FollowUpReportNumber { get; set; }
        public System.DateTime PeriodCoveredInitialReport { get; set; }
        public System.DateTime PeriodCoveredFinalReport { get; set; }
        public int IdOffice { get; set; }
        public string ContactPerson { get; set; }
        public string SubAgreement { get; set; }
        public int IDUnitTimeProjectDuration { get; set; }
        public int ProjectDuration { get; set; }
        public int IdImplementationModality { get; set; }
        public decimal TotalProjectValue { get; set; }
        public decimal UNHCRRrequiredValue { get; set; }
        public decimal AmountExecutedToDate { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ParameterDetail ParameterDetail2 { get; set; }
        public virtual ParameterDetail ParameterDetail3 { get; set; }
        public virtual ParameterDetail ParameterDetail4 { get; set; }
        public virtual ParameterDetail ParameterDetail5 { get; set; }
        public virtual ICollection<NationalPriorities> NationalPriorities { get; set; }
    }
}
