//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int IdEvent { get; set; }
        public int IdRequest { get; set; }
        public int IdAccommodationType { get; set; }
        public string EventName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int NumberParticipants { get; set; }
        public bool VideoBeam { get; set; }
        public bool Flipchart { get; set; }
        public int FlipchartQuantity { get; set; }
        public bool Internet { get; set; }
        public int MinimumBandwith { get; set; }
        public bool RentedComputers { get; set; }
        public int RentedComputerQuantity { get; set; }
        public int NumberComputers { get; set; }
        public string ComputerSpecifications { get; set; }
        public bool MicrophoneAmplification { get; set; }
        public string MicrophoneSpecifications { get; set; }
        public bool SimultaneusTranslation { get; set; }
        public string Language { get; set; }
        public string OtherResources { get; set; }
        public int NumberPassengers { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public int NumberRooms { get; set; }
        public bool Breakfast { get; set; }
        public bool CoffeBreakAM { get; set; }
        public bool Lunch { get; set; }
        public bool CoffeBreakPM { get; set; }
        public bool Dinner { get; set; }
        public bool Active { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual Request Request { get; set; }
    }
}
