//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralInformationRiskProfile
    {
        public GeneralInformationRiskProfile()
        {
            this.GeneralInformationRiskProfileUsers = new HashSet<GeneralInformationRiskProfileUsers>();
        }
    
        public int IdGeneralInformationRiskProfile { get; set; }
        public int IdAuthor { get; set; }
        public int IdOffice { get; set; }
        public int IdUnit { get; set; }
        public System.DateTime GeneralInformationDate { get; set; }
        public int IdEventType { get; set; }
        public int IdEventMedia { get; set; }
        public int IdAssociateEvent { get; set; }
        public int IdEventClassification { get; set; }
        public System.DateTime EventDate { get; set; }
        public int IdEventStatus { get; set; }
        public string VictimFirstName { get; set; }
        public string VictimSecondName { get; set; }
        public string VictimFirstLastName { get; set; }
        public string VictimSecondLastName { get; set; }
        public int IdGender { get; set; }
        public int IdPopulationType { get; set; }
        public int IdEthnicComunity { get; set; }
        public int IdFamilyType { get; set; }
        public int VictimAge { get; set; }
        public int IdProfile { get; set; }
        public int IdActivity { get; set; }
        public string FamilyNucleus { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationActivity { get; set; }
        public int IdCityEvent { get; set; }
        public string AdditionalGeographicLocationEvent { get; set; }
        public int IdResidenceCity { get; set; }
        public string AdditionalGeographicLocationResidence { get; set; }
        public int IdVictimizerGroup { get; set; }
        public int IdActor { get; set; }
        public string Description { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ParameterDetail ParameterDetail2 { get; set; }
        public virtual ParameterDetail ParameterDetail3 { get; set; }
        public virtual ParameterDetail ParameterDetail4 { get; set; }
        public virtual ParameterDetail ParameterDetail5 { get; set; }
        public virtual ParameterDetail ParameterDetail6 { get; set; }
        public virtual ParameterDetail ParameterDetail7 { get; set; }
        public virtual ParameterDetail ParameterDetail8 { get; set; }
        public virtual ParameterDetail ParameterDetail9 { get; set; }
        public virtual ParameterDetail ParameterDetail10 { get; set; }
        public virtual ParameterDetail ParameterDetail11 { get; set; }
        public virtual ParameterDetail ParameterDetail12 { get; set; }
        public virtual ParameterDetail ParameterDetail13 { get; set; }
        public virtual ParameterDetail ParameterDetail14 { get; set; }
        public virtual ParameterDetail ParameterDetail15 { get; set; }
        public virtual ParameterDetail ParameterDetail16 { get; set; }
        public virtual ParameterDetail ParameterDetail17 { get; set; }
        public virtual ICollection<GeneralInformationRiskProfileUsers> GeneralInformationRiskProfileUsers { get; set; }
    }
}
