//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralInformationAction
    {
        public GeneralInformationAction()
        {
            this.GeneralInformationActionUsers = new HashSet<GeneralInformationActionUsers>();
        }
    
        public int IdGeneralInformationAction { get; set; }
        public int IdAuthor { get; set; }
        public int IdOffice { get; set; }
        public int IdUnit { get; set; }
        public System.DateTime DateAction { get; set; }
        public int IdActionFrame { get; set; }
        public int IdAssociatedAction { get; set; }
        public int IdSubCategory { get; set; }
        public System.DateTime InitialDate { get; set; }
        public System.DateTime FinalDate { get; set; }
        public string StrategyObjetive { get; set; }
        public int IdActionType { get; set; }
        public int IdSpaceAction { get; set; }
        public int IdBeneficiary { get; set; }
        public int IdInstitution { get; set; }
        public string ComunityOrganization { get; set; }
        public string ReferenceData { get; set; }
        public Nullable<int> WomenBetween0And4 { get; set; }
        public Nullable<int> WomenBetween5And11 { get; set; }
        public Nullable<int> WomenBetween12And17 { get; set; }
        public Nullable<int> WomenBetween18And59 { get; set; }
        public Nullable<int> WomenBetween60AndMore { get; set; }
        public Nullable<int> MenBetween0And4 { get; set; }
        public Nullable<int> MenBetween5And11 { get; set; }
        public Nullable<int> MenBetween12And17 { get; set; }
        public Nullable<int> MenBetween18And59 { get; set; }
        public Nullable<int> MenBetween60AndMore { get; set; }
        public Nullable<int> TotalFamilies { get; set; }
        public Nullable<int> TotalPeople { get; set; }
        public int IdCity { get; set; }
        public string AdditionalGeographicLocation { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ParameterDetail ParameterDetail2 { get; set; }
        public virtual ParameterDetail ParameterDetail3 { get; set; }
        public virtual ParameterDetail ParameterDetail4 { get; set; }
        public virtual ParameterDetail ParameterDetail5 { get; set; }
        public virtual ParameterDetail ParameterDetail6 { get; set; }
        public virtual ParameterDetail ParameterDetail7 { get; set; }
        public virtual ParameterDetail ParameterDetail8 { get; set; }
        public virtual ParameterDetail ParameterDetail9 { get; set; }
        public virtual ParameterDetail ParameterDetail10 { get; set; }
        public virtual ICollection<GeneralInformationActionUsers> GeneralInformationActionUsers { get; set; }
    }
}
