//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralInformationEmergency
    {
        public GeneralInformationEmergency()
        {
            this.GeneralInformationEmergencyUsers = new HashSet<GeneralInformationEmergencyUsers>();
        }
    
        public int IdGeneralInformationEmergency { get; set; }
        public int IdVictimizerActor { get; set; }
        public int IdEmergencyCause { get; set; }
        public int IdEthnicComunity { get; set; }
        public int IdEventStatus { get; set; }
        public int IdCityExpulsion { get; set; }
        public int IdCityReception { get; set; }
        public int IdOffice { get; set; }
        public int IdEmergencyType { get; set; }
        public int IdEventType { get; set; }
        public int IdUnit { get; set; }
        public string Author { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<int> WomenBetween0And4 { get; set; }
        public Nullable<int> WomenBetween5And11 { get; set; }
        public Nullable<int> WomenBetween12And17 { get; set; }
        public Nullable<int> WomenBetween18And59 { get; set; }
        public Nullable<int> WomenBetween60AndMore { get; set; }
        public Nullable<int> MenBetween0And4 { get; set; }
        public Nullable<int> MenBetween5And11 { get; set; }
        public Nullable<int> MenBetween12And17 { get; set; }
        public Nullable<int> MenBetween18And59 { get; set; }
        public Nullable<int> MenBetween60AndMore { get; set; }
        public Nullable<int> TotalFamilies { get; set; }
        public Nullable<int> TotalPeople { get; set; }
        public string Description { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ParameterDetail ParameterDetail2 { get; set; }
        public virtual ParameterDetail ParameterDetail3 { get; set; }
        public virtual ParameterDetail ParameterDetail4 { get; set; }
        public virtual ParameterDetail ParameterDetail5 { get; set; }
        public virtual ParameterDetail ParameterDetail6 { get; set; }
        public virtual ParameterDetail ParameterDetail7 { get; set; }
        public virtual ParameterDetail ParameterDetail8 { get; set; }
        public virtual ParameterDetail ParameterDetail9 { get; set; }
        public virtual ICollection<GeneralInformationEmergencyUsers> GeneralInformationEmergencyUsers { get; set; }
    }
}
