//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int IdGoods { get; set; }
        public int IdRequest { get; set; }
        public Nullable<int> IdUnitMeasure { get; set; }
        public double Quantity { get; set; }
        public string Description { get; set; }
        public string ManufacturerBrand { get; set; }
        public string Model { get; set; }
        public string Reference { get; set; }
        public string Dimensions { get; set; }
        public string Color { get; set; }
        public string Capacity { get; set; }
        public string Power { get; set; }
        public string Other { get; set; }
        public string PlaceDelivery { get; set; }
        public string ContactPerson { get; set; }
        public System.DateTime ExpectedDeliveryDate { get; set; }
        public string Observations { get; set; }
        public bool Active { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual Request Request { get; set; }
    }
}
