//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItineraryInformation
    {
        public ItineraryInformation()
        {
            this.CostApproval = new HashSet<CostApproval>();
        }
    
        public int IdItineraryInformation { get; set; }
        public int IdStaffInformation { get; set; }
        public int IdCityFrom { get; set; }
        public int IdCityTo { get; set; }
        public System.DateTime DateOfficialBegin { get; set; }
        public System.DateTime DateOfficialEnd { get; set; }
        public string ReqTravelerBegin { get; set; }
        public string RegTravelerEnd { get; set; }
        public string ExcessBagg { get; set; }
        public string HouseHold { get; set; }
        public int RegisterAdded { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ICollection<CostApproval> CostApproval { get; set; }
        public virtual SatffInformation SatffInformation { get; set; }
    }
}
