//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACNUREntities : DbContext
    {
        public ACNUREntities()
            : base("name=ACNUREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GeneralInformationAction> GeneralInformationAction { get; set; }
        public virtual DbSet<GeneralInformationActionUsers> GeneralInformationActionUsers { get; set; }
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<ComponentsByModule> ComponentsByModule { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<ModuleUser> ModuleUser { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<OperationsModule> OperationsModule { get; set; }
        public virtual DbSet<OperationsModuleUser> OperationsModuleUser { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<ParameterDetail> ParameterDetail { get; set; }
        public virtual DbSet<StepsFlow> StepsFlow { get; set; }
        public virtual DbSet<StepsFlowModule> StepsFlowModule { get; set; }
        public virtual DbSet<StepsFlowModuleUser> StepsFlowModuleUser { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<CostApproval> CostApproval { get; set; }
        public virtual DbSet<ItineraryInformation> ItineraryInformation { get; set; }
        public virtual DbSet<PT8> PT8 { get; set; }
        public virtual DbSet<SatffInformation> SatffInformation { get; set; }
        public virtual DbSet<GeneralInformationEmergency> GeneralInformationEmergency { get; set; }
        public virtual DbSet<GeneralInformationEmergencyUsers> GeneralInformationEmergencyUsers { get; set; }
        public virtual DbSet<GeneralInformationEvent> GeneralInformationEvent { get; set; }
        public virtual DbSet<GeneralInformationEventUsers> GeneralInformationEventUsers { get; set; }
        public virtual DbSet<PressData> PressData { get; set; }
        public virtual DbSet<AnnexC> AnnexC { get; set; }
        public virtual DbSet<DataProject> DataProject { get; set; }
        public virtual DbSet<DescriptionOfTheTargetPopulation> DescriptionOfTheTargetPopulation { get; set; }
        public virtual DbSet<NationalPriorities> NationalPriorities { get; set; }
        public virtual DbSet<Weekly> Weekly { get; set; }
        public virtual DbSet<WeeklyRequest> WeeklyRequest { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<GeneralInformationRiskProfile> GeneralInformationRiskProfile { get; set; }
        public virtual DbSet<GeneralInformationRiskProfileUsers> GeneralInformationRiskProfileUsers { get; set; }
        public virtual DbSet<ParameterUserProcessed> ParameterUserProcessed { get; set; }
        public virtual DbSet<SessionComponentsByModule> SessionComponentsByModule { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<SessionTargetMailProcessed> SessionTargetMailProcessed { get; set; }
        public virtual DbSet<SessionTargetMails> SessionTargetMails { get; set; }
        public virtual DbSet<Attachments> Attachments { get; set; }
    }
}
