//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules
    {
        public Modules()
        {
            this.ComponentsByModule = new HashSet<ComponentsByModule>();
            this.ModuleUser = new HashSet<ModuleUser>();
            this.OperationsModule = new HashSet<OperationsModule>();
            this.StepsFlowModule = new HashSet<StepsFlowModule>();
        }
    
        public int IdModule { get; set; }
        public string ModuleName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ComponentsByModule> ComponentsByModule { get; set; }
        public virtual ICollection<ModuleUser> ModuleUser { get; set; }
        public virtual ICollection<OperationsModule> OperationsModule { get; set; }
        public virtual ICollection<StepsFlowModule> StepsFlowModule { get; set; }
    }
}
