//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NationalPriorities
    {
        public int IdNationalPriorities { get; set; }
        public int IdDataProject { get; set; }
        public string ThematicPriority { get; set; }
        public string TransversalPriority { get; set; }
        public System.DateTime UpdateDateContextoftheCurrentSituationandDevelopmentProject { get; set; }
        public string UpdatingtheContextoftheCurrentSituationandDevelopmentProject { get; set; }
        public string ProceduresForImplementation { get; set; }
        public string RelatedContributions { get; set; }
    
        public virtual DataProject DataProject { get; set; }
    }
}
