//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsModule
    {
        public OperationsModule()
        {
            this.OperationsModuleUser = new HashSet<OperationsModuleUser>();
        }
    
        public int IdOperationModule { get; set; }
        public int IdOperation { get; set; }
        public int IdModule { get; set; }
    
        public virtual Modules Modules { get; set; }
        public virtual Operations Operations { get; set; }
        public virtual ICollection<OperationsModuleUser> OperationsModuleUser { get; set; }
    }
}
