//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public Parameter()
        {
            this.ParameterDetail = new HashSet<ParameterDetail>();
        }
    
        public int IdParameter { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
        public bool Editable { get; set; }
        public bool Insertable { get; set; }
        public bool Removable { get; set; }
        public Nullable<int> IdParameterFather { get; set; }
    
        public virtual ICollection<ParameterDetail> ParameterDetail { get; set; }
    }
}
