//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressData
    {
        public int IdPressData { get; set; }
        public int IdCategoryPress { get; set; }
        public string Title { get; set; }
        public int IdSubcategoryPress { get; set; }
        public string WebLink { get; set; }
        public string MediaName { get; set; }
        public int IdEventLocationDepartament { get; set; }
        public int IdEventLocationMunicipality { get; set; }
        public int IdEventLocationSubMunicipality { get; set; }
        public string EventLocationCommunityOrOtherData { get; set; }
        public System.DateTime EventData { get; set; }
        public string Description { get; set; }
        public string IdAuthor { get; set; }
        public int IdOffice { get; set; }
        public int IdUnit { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ParameterDetail ParameterDetail2 { get; set; }
        public virtual ParameterDetail ParameterDetail3 { get; set; }
        public virtual ParameterDetail ParameterDetail4 { get; set; }
        public virtual ParameterDetail ParameterDetail5 { get; set; }
        public virtual ParameterDetail ParameterDetail6 { get; set; }
    }
}
