//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT8
    {
        public PT8()
        {
            this.SatffInformation = new HashSet<SatffInformation>();
        }
    
        public int IdPT8 { get; set; }
        public int IdAuthor { get; set; }
        public int IdOffice { get; set; }
        public int IdUnit { get; set; }
        public System.DateTime DatePT8 { get; set; }
        public int PT8Id { get; set; }
        public System.DateTime AditionalDate { get; set; }
        public string PreparedBy { get; set; }
        public int RegisterAdded { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ParameterDetail ParameterDetail2 { get; set; }
        public virtual ICollection<SatffInformation> SatffInformation { get; set; }
    }
}
