//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatffInformation
    {
        public SatffInformation()
        {
            this.ItineraryInformation = new HashSet<ItineraryInformation>();
        }
    
        public int IdStaffInformation { get; set; }
        public int IdPT8 { get; set; }
        public string SatffMemberName { get; set; }
        public string SatffMemberIndexNumber { get; set; }
        public string TitleGrade { get; set; }
        public string Nationality { get; set; }
        public string OfficeDuty { get; set; }
        public int IdUnit { get; set; }
        public double ExchangeRate { get; set; }
        public int IdTravelAgency { get; set; }
        public string Purpose { get; set; }
        public string SpecialInstruction { get; set; }
        public int RegisterAdded { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ICollection<ItineraryInformation> ItineraryInformation { get; set; }
        public virtual PT8 PT8 { get; set; }
    }
}
