//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int IdService { get; set; }
        public int IdServiceType { get; set; }
        public int IdRequest { get; set; }
        public string Context { get; set; }
        public int NumberDays { get; set; }
        public int HoursDay { get; set; }
        public string Description { get; set; }
        public string ServiceLocation { get; set; }
        public string Specifications { get; set; }
        public string ServiceResult { get; set; }
        public System.DateTime ExpectedDeliveryDate { get; set; }
        public System.DateTime PriorDeliveryDate { get; set; }
        public string DeliveryPlace { get; set; }
        public string ContactPerson { get; set; }
        public System.DateTime AlternativeDeliveryDate { get; set; }
        public string Observations { get; set; }
        public bool Active { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual Request Request { get; set; }
    }
}
