//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionComponentsByModule
    {
        public int IdSessionComponentByModule { get; set; }
        public int IdSession { get; set; }
        public int IdComponentByModule { get; set; }
        public int IdInformation { get; set; }
    
        public virtual ComponentsByModule ComponentsByModule { get; set; }
        public virtual Sessions Sessions { get; set; }
    }
}
