//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionTargetMailProcessed
    {
        public int IdSessionTargetMailProcessed { get; set; }
        public int IdSessionTargetMail { get; set; }
        public System.DateTime ProcessedDate { get; set; }
        public bool Processed { get; set; }
    
        public virtual SessionTargetMails SessionTargetMails { get; set; }
    }
}
