//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepsFlowModule
    {
        public StepsFlowModule()
        {
            this.StepsFlowModuleUser = new HashSet<StepsFlowModuleUser>();
        }
    
        public int IdStepFlowModule { get; set; }
        public int IdStepFlow { get; set; }
        public int IdModule { get; set; }
        public byte Sequence { get; set; }
    
        public virtual Modules Modules { get; set; }
        public virtual StepsFlow StepsFlow { get; set; }
        public virtual ICollection<StepsFlowModuleUser> StepsFlowModuleUser { get; set; }
    }
}
