//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.GeneralInformationActionUsers = new HashSet<GeneralInformationActionUsers>();
            this.Audit = new HashSet<Audit>();
            this.ModuleUser = new HashSet<ModuleUser>();
            this.OperationsModuleUser = new HashSet<OperationsModuleUser>();
            this.StepsFlowModuleUser = new HashSet<StepsFlowModuleUser>();
            this.GeneralInformationEventUsers = new HashSet<GeneralInformationEventUsers>();
            this.GeneralInformationRiskProfileUsers = new HashSet<GeneralInformationRiskProfileUsers>();
            this.GeneralInformationEmergencyUsers = new HashSet<GeneralInformationEmergencyUsers>();
        }
    
        public int IdUser { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Mail { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<GeneralInformationActionUsers> GeneralInformationActionUsers { get; set; }
        public virtual ICollection<Audit> Audit { get; set; }
        public virtual ICollection<ModuleUser> ModuleUser { get; set; }
        public virtual ICollection<OperationsModuleUser> OperationsModuleUser { get; set; }
        public virtual ICollection<StepsFlowModuleUser> StepsFlowModuleUser { get; set; }
        public virtual ICollection<GeneralInformationEventUsers> GeneralInformationEventUsers { get; set; }
        public virtual ICollection<GeneralInformationRiskProfileUsers> GeneralInformationRiskProfileUsers { get; set; }
        public virtual ICollection<GeneralInformationEmergencyUsers> GeneralInformationEmergencyUsers { get; set; }
    }
}
