//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weekly
    {
        public int IdWeekly { get; set; }
        public int IdWeeklyRequest { get; set; }
        public int IdCharacteristic { get; set; }
        public int IdSubCharacteristic { get; set; }
        public int IdDepartament { get; set; }
        public int IdMunicipality { get; set; }
        public string SubMunicipality { get; set; }
        public string Description { get; set; }
    
        public virtual ParameterDetail ParameterDetail { get; set; }
        public virtual ParameterDetail ParameterDetail1 { get; set; }
        public virtual ParameterDetail ParameterDetail2 { get; set; }
        public virtual ParameterDetail ParameterDetail3 { get; set; }
        public virtual WeeklyRequest WeeklyRequest { get; set; }
    }
}
