//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyRequest
    {
        public WeeklyRequest()
        {
            this.Weekly = new HashSet<Weekly>();
        }
    
        public int IdWeeklyRequest { get; set; }
        public int IdRequestUnit { get; set; }
        public string RequesterPerson { get; set; }
        public string DutyStation { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Responsible { get; set; }
    
        public virtual ICollection<Weekly> Weekly { get; set; }
    }
}
