//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAdministrator.Common
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinAdministrator.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Select objects to add.
        /// </summary>
        internal static string AddRemoveDetailEntities_SelectObjects
        {
            get
            {
                return ResourceManager.GetString("AddRemoveDetailEntities_SelectObjects", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        internal static string Confirmation_Caption
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Caption", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete this {0}?.
        /// </summary>
        internal static string Confirmation_Delete
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Click OK to reload the entity and lose unsaved changes. Click Cancel to continue editing data..
        /// </summary>
        internal static string Confirmation_Reset
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to reset layout? Reopen this view for the new layout to take effect..
        /// </summary>
        internal static string Confirmation_ResetLayout
        {
            get
            {
                return ResourceManager.GetString("Confirmation_ResetLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to save changes?.
        /// </summary>
        internal static string Confirmation_Save
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a You need to save the parent {0} entity before adding a new record. Do you want to save it now?.
        /// </summary>
        internal static string Confirmation_SaveParent
        {
            get
            {
                return ResourceManager.GetString("Confirmation_SaveParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a  *.
        /// </summary>
        internal static string Entity_Changed
        {
            get
            {
                return ResourceManager.GetString("Entity_Changed", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a  (Deleted).
        /// </summary>
        internal static string Entity_Deleted
        {
            get
            {
                return ResourceManager.GetString("Entity_Deleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a  (New).
        /// </summary>
        internal static string Entity_New
        {
            get
            {
                return ResourceManager.GetString("Entity_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a DataService Request Error.
        /// </summary>
        internal static string Exception_DataServiceRequestErrorCaption
        {
            get
            {
                return ResourceManager.GetString("Exception_DataServiceRequestErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Update Error.
        /// </summary>
        internal static string Exception_UpdateErrorCaption
        {
            get
            {
                return ResourceManager.GetString("Exception_UpdateErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Validation Error.
        /// </summary>
        internal static string Exception_ValidationErrorCaption
        {
            get
            {
                return ResourceManager.GetString("Exception_ValidationErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string Warning_Caption
        {
            get
            {
                return ResourceManager.GetString("Warning_Caption", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Some fields contain invalid data. Click OK to close the page and lose unsaved changes. Press Cancel to continue editing data..
        /// </summary>
        internal static string Warning_SomeFieldsContainInvalidData
        {
            get
            {
                return ResourceManager.GetString("Warning_SomeFieldsContainInvalidData", resourceCulture);
            }
        }
    }
}
