//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class AnnexC
    {
    
    	/// <summary>
        /// Atributo IdAnnexC
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAnnexC { get; set; }
    
    	/// <summary>
        /// Atributo IdProgramCycle
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProgramCycle { get; set; }
    
    	/// <summary>
        /// Atributo Author
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Author { get; set; }
    
    	/// <summary>
        /// Atributo DateRegister
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime DateRegister { get; set; }
    
    	/// <summary>
        /// Atributo Project
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Project { get; set; }
    
    	/// <summary>
        /// Atributo IdPriority
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdPriority { get; set; }
    
    	/// <summary>
        /// Atributo IdStrategy
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdStrategy { get; set; }
    
    	/// <summary>
        /// Atributo IdFocusRightsGroup
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdFocusRightsGroup { get; set; }
    
    	/// <summary>
        /// Atributo IdMSRPRightsGroup
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdMSRPRightsGroup { get; set; }
    
    	/// <summary>
        /// Atributo IdFocusObjective
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdFocusObjective { get; set; }
    
    	/// <summary>
        /// Atributo IdMSRPObjective
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdMSRPObjective { get; set; }
    
    	/// <summary>
        /// Atributo IdFocusImpactIndicatorOutput
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdFocusImpactIndicatorOutput { get; set; }
    
    	/// <summary>
        /// Atributo IdMSRPOutput
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdMSRPOutput { get; set; }
    
    	/// <summary>
        /// Atributo ProjectTitle
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ProjectTitle { get; set; }
    
    	/// <summary>
        /// Atributo SubAgreement
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string SubAgreement { get; set; }
    
    	/// <summary>
        /// Atributo IdImplementerCode
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdImplementerCode { get; set; }
    
    	/// <summary>
        /// Atributo IdImplementationMechanism
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdImplementationMechanism { get; set; }
    
    	/// <summary>
        /// Atributo IdOfficeRisponsible
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdOfficeRisponsible { get; set; }
    
    	/// <summary>
        /// Atributo IdSite
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSite { get; set; }
    
    	/// <summary>
        /// Atributo IdCostCentre
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCostCentre { get; set; }
    
    	/// <summary>
        /// Atributo IdProjectLocationDepartament
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProjectLocationDepartament { get; set; }
    
    	/// <summary>
        /// Atributo IdProjectLocationMunicipality
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProjectLocationMunicipality { get; set; }
    
    	/// <summary>
        /// Atributo IdProjectLocationSubMunicipality
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProjectLocationSubMunicipality { get; set; }
    
    	/// <summary>
        /// Atributo ProjectLocationComunityName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int ProjectLocationComunityName { get; set; }
    
    	/// <summary>
        /// Atributo IdUNIT
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdUNIT { get; set; }
    
    	/// <summary>
        /// Atributo IdCurrency
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCurrency { get; set; }
    
    	/// <summary>
        /// Atributo Budget
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public decimal Budget { get; set; }
    
    	/// <summary>
        /// Atributo USD
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string USD { get; set; }
    
    	/// <summary>
        /// Atributo Donor
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Donor { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail1
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail2
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail2 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail3
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail3 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail4 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail5
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail5 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail6
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail6 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail7
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail7 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail8
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail8 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail9
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail9 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail10
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail10 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail11
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail11 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail12
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail12 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail13
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail13 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail14
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail14 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail15
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail15 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail16
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail16 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail17
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail17 { get; set; }
    }
}
