//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class Attachments
    {
    
    	/// <summary>
        /// Atributo IdAttachment
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAttachment { get; set; }
    
    	/// <summary>
        /// Atributo IdComponentByModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdComponentByModule { get; set; }
    
    	/// <summary>
        /// Atributo IdInformation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdInformation { get; set; }
    
    	/// <summary>
        /// Atributo AttachmentName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string AttachmentName { get; set; }
    
    	/// <summary>
        /// Atributo Description
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Description { get; set; }
    
    	/// <summary>
        /// Atributo IdAttachmentType
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAttachmentType { get; set; }
    
    	/// <summary>
        /// Atributo IdAttachmentCondition
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAttachmentCondition { get; set; }
    
    	/// <summary>
        /// Atributo Attachment
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public byte[] Attachment { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ComponentsByModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ComponentsByModule ComponentsByModule { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail1
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    }
}
