//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class Audit
    {
    
    	/// <summary>
        /// Atributo IdAudit
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAudit { get; set; }
    
    	/// <summary>
        /// Atributo IdUser
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdUser { get; set; }
    
    	/// <summary>
        /// Atributo ModificationDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime ModificationDate { get; set; }
    
    	/// <summary>
        /// Atributo EntityBefore
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public byte[] EntityBefore { get; set; }
    
    	/// <summary>
        /// Atributo EntityAfter
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public byte[] EntityAfter { get; set; }
    
    	/// <summary>
        /// Atributo IdKeyEntity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdKeyEntity { get; set; }
    
    	/// <summary>
        /// Atributo IdKeyConsult
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string IdKeyConsult { get; set; }
    
    	/// <summary>
        /// Atributo IPAdress
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string IPAdress { get; set; }
    
    	/// <summary>
        /// Atributo IdProcessEntity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProcessEntity { get; set; }
    
    	/// <summary>
        /// Atributo Operation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Operation { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion Users
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Users Users { get; set; }
    }
}
