//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class ComponentsByModule
    {
    	/// <summary>
        /// Constructor ComponentsByModule
        /// </summary>
        public ComponentsByModule()
        {
            this.Attachments = new HashSet<Attachments>();
            this.SessionComponentsByModule = new HashSet<SessionComponentsByModule>();
        }
    
    
    	/// <summary>
        /// Atributo IdComponentByModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdComponentByModule { get; set; }
    
    	/// <summary>
        /// Atributo Name
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Name { get; set; }
    
    	/// <summary>
        /// Atributo IdModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdModule { get; set; }
    
    	/// <summary>
        /// Atributo Description
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Description { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion Attachments
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<Attachments> Attachments { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Modules
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Modules Modules { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion SessionComponentsByModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<SessionComponentsByModule> SessionComponentsByModule { get; set; }
    }
}
