//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class DataProject
    {
    	/// <summary>
        /// Constructor DataProject
        /// </summary>
        public DataProject()
        {
            this.NationalPriorities = new HashSet<NationalPriorities>();
        }
    
    
    	/// <summary>
        /// Atributo IdDataProject
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdDataProject { get; set; }
    
    	/// <summary>
        /// Atributo ProjectTitle
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ProjectTitle { get; set; }
    
    	/// <summary>
        /// Atributo IdProjectlocationDepartament
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProjectlocationDepartament { get; set; }
    
    	/// <summary>
        /// Atributo IdProjectlocationMunicipality
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProjectlocationMunicipality { get; set; }
    
    	/// <summary>
        /// Atributo IdProjectlocationSubMunicipality
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProjectlocationSubMunicipality { get; set; }
    
    	/// <summary>
        /// Atributo ImplementationPartners
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ImplementationPartners { get; set; }
    
    	/// <summary>
        /// Atributo FollowUpReportNumber
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public decimal FollowUpReportNumber { get; set; }
    
    	/// <summary>
        /// Atributo PeriodCoveredInitialReport
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime PeriodCoveredInitialReport { get; set; }
    
    	/// <summary>
        /// Atributo PeriodCoveredFinalReport
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime PeriodCoveredFinalReport { get; set; }
    
    	/// <summary>
        /// Atributo IdOffice
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdOffice { get; set; }
    
    	/// <summary>
        /// Atributo ContactPerson
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ContactPerson { get; set; }
    
    	/// <summary>
        /// Atributo SubAgreement
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string SubAgreement { get; set; }
    
    	/// <summary>
        /// Atributo IDUnitTimeProjectDuration
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IDUnitTimeProjectDuration { get; set; }
    
    	/// <summary>
        /// Atributo ProjectDuration
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int ProjectDuration { get; set; }
    
    	/// <summary>
        /// Atributo IdImplementationModality
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdImplementationModality { get; set; }
    
    	/// <summary>
        /// Atributo TotalProjectValue
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public decimal TotalProjectValue { get; set; }
    
    	/// <summary>
        /// Atributo UNHCRRrequiredValue
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public decimal UNHCRRrequiredValue { get; set; }
    
    	/// <summary>
        /// Atributo AmountExecutedToDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public decimal AmountExecutedToDate { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail1
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail2
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail2 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail3
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail3 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail4 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail5
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail5 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion NationalPriorities
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<NationalPriorities> NationalPriorities { get; set; }
    }
}
