//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class DescriptionOfTheTargetPopulation
    {
    
    	/// <summary>
        /// Atributo IdDescriptionOfTheTargetPopulation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdDescriptionOfTheTargetPopulation { get; set; }
    
    	/// <summary>
        /// Atributo IdDataProject
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdDataProject { get; set; }
    
    	/// <summary>
        /// Atributo IdTypeBeneficiaries
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdTypeBeneficiaries { get; set; }
    
    	/// <summary>
        /// Atributo IdTypePopulation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdTypePopulation { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween0And4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int WomenBetween0And4 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween5And11
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int WomenBetween5And11 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween12And17
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int WomenBetween12And17 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween18And59
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int WomenBetween18And59 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween60AndMore
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int WomenBetween60AndMore { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween0And4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int MenBetween0And4 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween5And11
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int MenBetween5And11 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween12And17
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int MenBetween12And17 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween18And59
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int MenBetween18And59 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween60AndMore
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int MenBetween60AndMore { get; set; }
    
    	/// <summary>
        /// Atributo TotalFamilies
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int TotalFamilies { get; set; }
    
    	/// <summary>
        /// Atributo TotalPeople
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int TotalPeople { get; set; }
    
    	/// <summary>
        /// Atributo TotalCivilServant
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> TotalCivilServant { get; set; }
    
    	/// <summary>
        /// Atributo NarrativeDescriptionOfTheDirectBeneficiaries
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string NarrativeDescriptionOfTheDirectBeneficiaries { get; set; }
    }
}
