//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class Events
    {
    
    	/// <summary>
        /// Atributo IdEvent
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEvent { get; set; }
    
    	/// <summary>
        /// Atributo IdRequest
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdRequest { get; set; }
    
    	/// <summary>
        /// Atributo IdAccommodationType
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAccommodationType { get; set; }
    
    	/// <summary>
        /// Atributo EventName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string EventName { get; set; }
    
    	/// <summary>
        /// Atributo StartDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime StartDate { get; set; }
    
    	/// <summary>
        /// Atributo EndDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime EndDate { get; set; }
    
    	/// <summary>
        /// Atributo StartTime
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.TimeSpan StartTime { get; set; }
    
    	/// <summary>
        /// Atributo EndTime
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.TimeSpan EndTime { get; set; }
    
    	/// <summary>
        /// Atributo NumberParticipants
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int NumberParticipants { get; set; }
    
    	/// <summary>
        /// Atributo VideoBeam
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool VideoBeam { get; set; }
    
    	/// <summary>
        /// Atributo Flipchart
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Flipchart { get; set; }
    
    	/// <summary>
        /// Atributo FlipchartQuantity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int FlipchartQuantity { get; set; }
    
    	/// <summary>
        /// Atributo Internet
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Internet { get; set; }
    
    	/// <summary>
        /// Atributo MinimumBandwith
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int MinimumBandwith { get; set; }
    
    	/// <summary>
        /// Atributo RentedComputers
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool RentedComputers { get; set; }
    
    	/// <summary>
        /// Atributo RentedComputerQuantity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int RentedComputerQuantity { get; set; }
    
    	/// <summary>
        /// Atributo NumberComputers
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int NumberComputers { get; set; }
    
    	/// <summary>
        /// Atributo ComputerSpecifications
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ComputerSpecifications { get; set; }
    
    	/// <summary>
        /// Atributo MicrophoneAmplification
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool MicrophoneAmplification { get; set; }
    
    	/// <summary>
        /// Atributo MicrophoneSpecifications
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string MicrophoneSpecifications { get; set; }
    
    	/// <summary>
        /// Atributo SimultaneusTranslation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool SimultaneusTranslation { get; set; }
    
    	/// <summary>
        /// Atributo Language
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Language { get; set; }
    
    	/// <summary>
        /// Atributo OtherResources
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string OtherResources { get; set; }
    
    	/// <summary>
        /// Atributo NumberPassengers
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int NumberPassengers { get; set; }
    
    	/// <summary>
        /// Atributo Origin
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Origin { get; set; }
    
    	/// <summary>
        /// Atributo Destination
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Destination { get; set; }
    
    	/// <summary>
        /// Atributo NumberRooms
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int NumberRooms { get; set; }
    
    	/// <summary>
        /// Atributo Breakfast
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Breakfast { get; set; }
    
    	/// <summary>
        /// Atributo CoffeBreakAM
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool CoffeBreakAM { get; set; }
    
    	/// <summary>
        /// Atributo Lunch
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Lunch { get; set; }
    
    	/// <summary>
        /// Atributo CoffeBreakPM
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool CoffeBreakPM { get; set; }
    
    	/// <summary>
        /// Atributo Dinner
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Dinner { get; set; }
    
    	/// <summary>
        /// Atributo Active
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Active { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Request
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Request Request { get; set; }
    }
}
