//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class GeneralInformationEvent
    {
    	/// <summary>
        /// Constructor GeneralInformationEvent
        /// </summary>
        public GeneralInformationEvent()
        {
            this.GeneralInformationEventUsers = new HashSet<GeneralInformationEventUsers>();
        }
    
    
    	/// <summary>
        /// Atributo IdGeneralInformationEvent
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdGeneralInformationEvent { get; set; }
    
    	/// <summary>
        /// Atributo IdAuthor
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAuthor { get; set; }
    
    	/// <summary>
        /// Atributo IdOffice
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdOffice { get; set; }
    
    	/// <summary>
        /// Atributo IdUnit
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdUnit { get; set; }
    
    	/// <summary>
        /// Atributo EventDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime EventDate { get; set; }
    
    	/// <summary>
        /// Atributo IdCategory
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCategory { get; set; }
    
    	/// <summary>
        /// Atributo IdSubCategory
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSubCategory { get; set; }
    
    	/// <summary>
        /// Atributo IdInformationSource
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdInformationSource { get; set; }
    
    	/// <summary>
        /// Atributo Title
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Title { get; set; }
    
    	/// <summary>
        /// Atributo Url
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Url { get; set; }
    
    	/// <summary>
        /// Atributo IdCity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCity { get; set; }
    
    	/// <summary>
        /// Atributo AdditionalGeographicLocation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string AdditionalGeographicLocation { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail1
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail2
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail2 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail3
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail3 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail4 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail5
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail5 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail6
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail6 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion GeneralInformationEventUsers
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<GeneralInformationEventUsers> GeneralInformationEventUsers { get; set; }
    }
}
