//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class GeneralInformationRiskProfile
    {
    	/// <summary>
        /// Constructor GeneralInformationRiskProfile
        /// </summary>
        public GeneralInformationRiskProfile()
        {
            this.GeneralInformationRiskProfileUsers = new HashSet<GeneralInformationRiskProfileUsers>();
        }
    
    
    	/// <summary>
        /// Atributo IdGeneralInformationRiskProfile
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdGeneralInformationRiskProfile { get; set; }
    
    	/// <summary>
        /// Atributo IdAuthor
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAuthor { get; set; }
    
    	/// <summary>
        /// Atributo IdOffice
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdOffice { get; set; }
    
    	/// <summary>
        /// Atributo IdUnit
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdUnit { get; set; }
    
    	/// <summary>
        /// Atributo GeneralInformationDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime GeneralInformationDate { get; set; }
    
    	/// <summary>
        /// Atributo IdEventType
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEventType { get; set; }
    
    	/// <summary>
        /// Atributo IdEventMedia
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEventMedia { get; set; }
    
    	/// <summary>
        /// Atributo IdAssociateEvent
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAssociateEvent { get; set; }
    
    	/// <summary>
        /// Atributo IdEventClassification
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEventClassification { get; set; }
    
    	/// <summary>
        /// Atributo EventDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime EventDate { get; set; }
    
    	/// <summary>
        /// Atributo IdEventStatus
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEventStatus { get; set; }
    
    	/// <summary>
        /// Atributo VictimFirstName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string VictimFirstName { get; set; }
    
    	/// <summary>
        /// Atributo VictimSecondName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string VictimSecondName { get; set; }
    
    	/// <summary>
        /// Atributo VictimFirstLastName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string VictimFirstLastName { get; set; }
    
    	/// <summary>
        /// Atributo VictimSecondLastName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string VictimSecondLastName { get; set; }
    
    	/// <summary>
        /// Atributo IdGender
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdGender { get; set; }
    
    	/// <summary>
        /// Atributo IdPopulationType
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdPopulationType { get; set; }
    
    	/// <summary>
        /// Atributo IdEthnicComunity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEthnicComunity { get; set; }
    
    	/// <summary>
        /// Atributo IdFamilyType
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdFamilyType { get; set; }
    
    	/// <summary>
        /// Atributo VictimAge
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int VictimAge { get; set; }
    
    	/// <summary>
        /// Atributo IdProfile
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProfile { get; set; }
    
    	/// <summary>
        /// Atributo IdActivity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdActivity { get; set; }
    
    	/// <summary>
        /// Atributo FamilyNucleus
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string FamilyNucleus { get; set; }
    
    	/// <summary>
        /// Atributo OrganizationName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string OrganizationName { get; set; }
    
    	/// <summary>
        /// Atributo OrganizationActivity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string OrganizationActivity { get; set; }
    
    	/// <summary>
        /// Atributo IdCityEvent
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCityEvent { get; set; }
    
    	/// <summary>
        /// Atributo AdditionalGeographicLocationEvent
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string AdditionalGeographicLocationEvent { get; set; }
    
    	/// <summary>
        /// Atributo IdResidenceCity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdResidenceCity { get; set; }
    
    	/// <summary>
        /// Atributo AdditionalGeographicLocationResidence
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string AdditionalGeographicLocationResidence { get; set; }
    
    	/// <summary>
        /// Atributo IdVictimizerGroup
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdVictimizerGroup { get; set; }
    
    	/// <summary>
        /// Atributo IdActor
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdActor { get; set; }
    
    	/// <summary>
        /// Atributo Description
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Description { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail1
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail2
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail2 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail3
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail3 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail4 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail5
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail5 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail6
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail6 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail7
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail7 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail8
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail8 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail9
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail9 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail10
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail10 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail11
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail11 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail12
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail12 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail13
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail13 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail14
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail14 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail15
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail15 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail16
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail16 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail17
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail17 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion GeneralInformationRiskProfileUsers
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<GeneralInformationRiskProfileUsers> GeneralInformationRiskProfileUsers { get; set; }
    }
}
