//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class GeneralInformationAction
    {
    	/// <summary>
        /// Constructor GeneralInformationAction
        /// </summary>
        public GeneralInformationAction()
        {
            this.GeneralInformationActionUsers = new HashSet<GeneralInformationActionUsers>();
        }
    
    
    	/// <summary>
        /// Atributo IdGeneralInformationAction
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdGeneralInformationAction { get; set; }
    
    	/// <summary>
        /// Atributo IdAuthor
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAuthor { get; set; }
    
    	/// <summary>
        /// Atributo IdOffice
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdOffice { get; set; }
    
    	/// <summary>
        /// Atributo IdUnit
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdUnit { get; set; }
    
    	/// <summary>
        /// Atributo DateAction
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime DateAction { get; set; }
    
    	/// <summary>
        /// Atributo IdActionFrame
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdActionFrame { get; set; }
    
    	/// <summary>
        /// Atributo IdAssociatedAction
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdAssociatedAction { get; set; }
    
    	/// <summary>
        /// Atributo IdSubCategory
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSubCategory { get; set; }
    
    	/// <summary>
        /// Atributo InitialDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime InitialDate { get; set; }
    
    	/// <summary>
        /// Atributo FinalDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime FinalDate { get; set; }
    
    	/// <summary>
        /// Atributo StrategyObjetive
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string StrategyObjetive { get; set; }
    
    	/// <summary>
        /// Atributo IdActionType
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdActionType { get; set; }
    
    	/// <summary>
        /// Atributo IdSpaceAction
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSpaceAction { get; set; }
    
    	/// <summary>
        /// Atributo IdBeneficiary
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdBeneficiary { get; set; }
    
    	/// <summary>
        /// Atributo IdInstitution
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdInstitution { get; set; }
    
    	/// <summary>
        /// Atributo ComunityOrganization
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ComunityOrganization { get; set; }
    
    	/// <summary>
        /// Atributo ReferenceData
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ReferenceData { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween0And4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween0And4 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween5And11
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween5And11 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween12And17
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween12And17 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween18And59
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween18And59 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween60AndMore
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween60AndMore { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween0And4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween0And4 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween5And11
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween5And11 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween12And17
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween12And17 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween18And59
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween18And59 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween60AndMore
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween60AndMore { get; set; }
    
    	/// <summary>
        /// Atributo TotalFamilies
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> TotalFamilies { get; set; }
    
    	/// <summary>
        /// Atributo TotalPeople
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> TotalPeople { get; set; }
    
    	/// <summary>
        /// Atributo IdCity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCity { get; set; }
    
    	/// <summary>
        /// Atributo AdditionalGeographicLocation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string AdditionalGeographicLocation { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail1
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail2
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail2 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail3
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail3 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail4 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail5
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail5 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail6
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail6 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail7
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail7 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail8
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail8 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail9
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail9 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail10
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail10 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion GeneralInformationActionUsers
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<GeneralInformationActionUsers> GeneralInformationActionUsers { get; set; }
    }
}
