//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class GeneralInformationEmergency
    {
    	/// <summary>
        /// Constructor GeneralInformationEmergency
        /// </summary>
        public GeneralInformationEmergency()
        {
            this.GeneralInformationEmergencyUsers = new HashSet<GeneralInformationEmergencyUsers>();
        }
    
    
    	/// <summary>
        /// Atributo IdGeneralInformationEmergency
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdGeneralInformationEmergency { get; set; }
    
    	/// <summary>
        /// Atributo IdVictimizerActor
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdVictimizerActor { get; set; }
    
    	/// <summary>
        /// Atributo IdEmergencyCause
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEmergencyCause { get; set; }
    
    	/// <summary>
        /// Atributo IdEthnicComunity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEthnicComunity { get; set; }
    
    	/// <summary>
        /// Atributo IdEventStatus
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEventStatus { get; set; }
    
    	/// <summary>
        /// Atributo IdCityExpulsion
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCityExpulsion { get; set; }
    
    	/// <summary>
        /// Atributo IdCityReception
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCityReception { get; set; }
    
    	/// <summary>
        /// Atributo IdOffice
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdOffice { get; set; }
    
    	/// <summary>
        /// Atributo IdEmergencyType
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEmergencyType { get; set; }
    
    	/// <summary>
        /// Atributo IdEventType
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdEventType { get; set; }
    
    	/// <summary>
        /// Atributo IdUnit
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdUnit { get; set; }
    
    	/// <summary>
        /// Atributo Author
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Author { get; set; }
    
    	/// <summary>
        /// Atributo ReportDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime ReportDate { get; set; }
    
    	/// <summary>
        /// Atributo EventDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime EventDate { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween0And4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween0And4 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween5And11
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween5And11 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween12And17
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween12And17 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween18And59
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween18And59 { get; set; }
    
    	/// <summary>
        /// Atributo WomenBetween60AndMore
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> WomenBetween60AndMore { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween0And4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween0And4 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween5And11
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween5And11 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween12And17
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween12And17 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween18And59
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween18And59 { get; set; }
    
    	/// <summary>
        /// Atributo MenBetween60AndMore
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> MenBetween60AndMore { get; set; }
    
    	/// <summary>
        /// Atributo TotalFamilies
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> TotalFamilies { get; set; }
    
    	/// <summary>
        /// Atributo TotalPeople
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> TotalPeople { get; set; }
    
    	/// <summary>
        /// Atributo Description
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Description { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail1
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail2
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail2 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail3
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail3 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail4
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail4 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail5
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail5 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail6
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail6 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail7
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail7 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail8
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail8 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail9
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail9 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion GeneralInformationEmergencyUsers
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<GeneralInformationEmergencyUsers> GeneralInformationEmergencyUsers { get; set; }
    }
}
