//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class GeneralInformationEventUsers
    {
    
    	/// <summary>
        /// Atributo IdGeneralInformationEventUser
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdGeneralInformationEventUser { get; set; }
    
    	/// <summary>
        /// Atributo IdGeneralInformationEvent
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdGeneralInformationEvent { get; set; }
    
    	/// <summary>
        /// Atributo IdUser
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdUser { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion Users
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Users Users { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion GeneralInformationEvent
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual GeneralInformationEvent GeneralInformationEvent { get; set; }
    }
}
