//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class Goods
    {
    
    	/// <summary>
        /// Atributo IdGoods
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdGoods { get; set; }
    
    	/// <summary>
        /// Atributo IdRequest
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdRequest { get; set; }
    
    	/// <summary>
        /// Atributo IdUnitMeasure
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> IdUnitMeasure { get; set; }
    
    	/// <summary>
        /// Atributo Quantity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public double Quantity { get; set; }
    
    	/// <summary>
        /// Atributo Description
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Description { get; set; }
    
    	/// <summary>
        /// Atributo ManufacturerBrand
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ManufacturerBrand { get; set; }
    
    	/// <summary>
        /// Atributo Model
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Model { get; set; }
    
    	/// <summary>
        /// Atributo Reference
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Reference { get; set; }
    
    	/// <summary>
        /// Atributo Dimensions
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Dimensions { get; set; }
    
    	/// <summary>
        /// Atributo Color
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Color { get; set; }
    
    	/// <summary>
        /// Atributo Capacity
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Capacity { get; set; }
    
    	/// <summary>
        /// Atributo Power
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Power { get; set; }
    
    	/// <summary>
        /// Atributo Other
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Other { get; set; }
    
    	/// <summary>
        /// Atributo PlaceDelivery
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string PlaceDelivery { get; set; }
    
    	/// <summary>
        /// Atributo ContactPerson
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ContactPerson { get; set; }
    
    	/// <summary>
        /// Atributo ExpectedDeliveryDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime ExpectedDeliveryDate { get; set; }
    
    	/// <summary>
        /// Atributo Observations
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Observations { get; set; }
    
    	/// <summary>
        /// Atributo Active
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Active { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Request
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Request Request { get; set; }
    }
}
