//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class ItineraryInformation
    {
    	/// <summary>
        /// Constructor ItineraryInformation
        /// </summary>
        public ItineraryInformation()
        {
            this.CostApproval = new HashSet<CostApproval>();
        }
    
    
    	/// <summary>
        /// Atributo IdItineraryInformation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdItineraryInformation { get; set; }
    
    	/// <summary>
        /// Atributo IdStaffInformation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdStaffInformation { get; set; }
    
    	/// <summary>
        /// Atributo IdCityFrom
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCityFrom { get; set; }
    
    	/// <summary>
        /// Atributo IdCityTo
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdCityTo { get; set; }
    
    	/// <summary>
        /// Atributo DateOfficialBegin
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime DateOfficialBegin { get; set; }
    
    	/// <summary>
        /// Atributo DateOfficialEnd
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime DateOfficialEnd { get; set; }
    
    	/// <summary>
        /// Atributo ReqTravelerBegin
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ReqTravelerBegin { get; set; }
    
    	/// <summary>
        /// Atributo RegTravelerEnd
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string RegTravelerEnd { get; set; }
    
    	/// <summary>
        /// Atributo ExcessBagg
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ExcessBagg { get; set; }
    
    	/// <summary>
        /// Atributo HouseHold
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string HouseHold { get; set; }
    
    	/// <summary>
        /// Atributo RegisterAdded
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int RegisterAdded { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail1
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion CostApproval
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<CostApproval> CostApproval { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion SatffInformation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual SatffInformation SatffInformation { get; set; }
    }
}
