//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class Modules
    {
    	/// <summary>
        /// Constructor Modules
        /// </summary>
        public Modules()
        {
            this.ComponentsByModule = new HashSet<ComponentsByModule>();
            this.ModuleUser = new HashSet<ModuleUser>();
            this.OperationsModule = new HashSet<OperationsModule>();
            this.StepsFlowModule = new HashSet<StepsFlowModule>();
        }
    
    
    	/// <summary>
        /// Atributo IdModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdModule { get; set; }
    
    	/// <summary>
        /// Atributo ModuleName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ModuleName { get; set; }
    
    	/// <summary>
        /// Atributo Description
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Description { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ComponentsByModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<ComponentsByModule> ComponentsByModule { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ModuleUser
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<ModuleUser> ModuleUser { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion OperationsModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<OperationsModule> OperationsModule { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion StepsFlowModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<StepsFlowModule> StepsFlowModule { get; set; }
    }
}
