//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class ModuleUser
    {
    
    	/// <summary>
        /// Atributo IdModuleUser
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdModuleUser { get; set; }
    
    	/// <summary>
        /// Atributo IdModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdModule { get; set; }
    
    	/// <summary>
        /// Atributo IdUser
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdUser { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion Modules
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Modules Modules { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Users
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Users Users { get; set; }
    }
}
