//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class NationalPriorities
    {
    
    	/// <summary>
        /// Atributo IdNationalPriorities
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdNationalPriorities { get; set; }
    
    	/// <summary>
        /// Atributo IdDataProject
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdDataProject { get; set; }
    
    	/// <summary>
        /// Atributo ThematicPriority
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ThematicPriority { get; set; }
    
    	/// <summary>
        /// Atributo TransversalPriority
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string TransversalPriority { get; set; }
    
    	/// <summary>
        /// Atributo UpdateDateContextoftheCurrentSituationandDevelopmentProject
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime UpdateDateContextoftheCurrentSituationandDevelopmentProject { get; set; }
    
    	/// <summary>
        /// Atributo UpdatingtheContextoftheCurrentSituationandDevelopmentProject
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string UpdatingtheContextoftheCurrentSituationandDevelopmentProject { get; set; }
    
    	/// <summary>
        /// Atributo ProceduresForImplementation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ProceduresForImplementation { get; set; }
    
    	/// <summary>
        /// Atributo RelatedContributions
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string RelatedContributions { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion DataProject
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual DataProject DataProject { get; set; }
    }
}
