//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class OperationsModule
    {
    	/// <summary>
        /// Constructor OperationsModule
        /// </summary>
        public OperationsModule()
        {
            this.OperationsModuleUser = new HashSet<OperationsModuleUser>();
        }
    
    
    	/// <summary>
        /// Atributo IdOperationModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdOperationModule { get; set; }
    
    	/// <summary>
        /// Atributo IdOperation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdOperation { get; set; }
    
    	/// <summary>
        /// Atributo IdModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdModule { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion Modules
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Modules Modules { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Operations
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Operations Operations { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion OperationsModuleUser
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<OperationsModuleUser> OperationsModuleUser { get; set; }
    }
}
