//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class Parameter
    {
    	/// <summary>
        /// Constructor Parameter
        /// </summary>
        public Parameter()
        {
            this.ParameterDetail = new HashSet<ParameterDetail>();
        }
    
    
    	/// <summary>
        /// Atributo IdParameter
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdParameter { get; set; }
    
    	/// <summary>
        /// Atributo Name
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Name { get; set; }
    
    	/// <summary>
        /// Atributo Description
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Description { get; set; }
    
    	/// <summary>
        /// Atributo State
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool State { get; set; }
    
    	/// <summary>
        /// Atributo Editable
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Editable { get; set; }
    
    	/// <summary>
        /// Atributo Insertable
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Insertable { get; set; }
    
    	/// <summary>
        /// Atributo Removable
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Removable { get; set; }
    
    	/// <summary>
        /// Atributo IdParameterFather
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> IdParameterFather { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<ParameterDetail> ParameterDetail { get; set; }
    }
}
