//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class Request
    {
    	/// <summary>
        /// Constructor Request
        /// </summary>
        public Request()
        {
            this.Events = new HashSet<Events>();
            this.Goods = new HashSet<Goods>();
            this.Services = new HashSet<Services>();
        }
    
    
    	/// <summary>
        /// Atributo IdRequest
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdRequest { get; set; }
    
    	/// <summary>
        /// Atributo IdRequestUnit
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdRequestUnit { get; set; }
    
    	/// <summary>
        /// Atributo RequesterPerson
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string RequesterPerson { get; set; }
    
    	/// <summary>
        /// Atributo DutyStation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string DutyStation { get; set; }
    
    	/// <summary>
        /// Atributo RequestDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime RequestDate { get; set; }
    
    	/// <summary>
        /// Atributo Responsible
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Responsible { get; set; }
    
    	/// <summary>
        /// Atributo BackgroundRationale
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string BackgroundRationale { get; set; }
    
    	/// <summary>
        /// Atributo DeliveryLocation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string DeliveryLocation { get; set; }
    
    	/// <summary>
        /// Atributo EstimatedDeliveryDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime EstimatedDeliveryDate { get; set; }
    
    	/// <summary>
        /// Atributo Active
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Active { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Events
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<Events> Events { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Goods
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<Goods> Goods { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Services
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<Services> Services { get; set; }
    }
}
