//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class SatffInformation
    {
    	/// <summary>
        /// Constructor SatffInformation
        /// </summary>
        public SatffInformation()
        {
            this.ItineraryInformation = new HashSet<ItineraryInformation>();
        }
    
    
    	/// <summary>
        /// Atributo IdStaffInformation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdStaffInformation { get; set; }
    
    	/// <summary>
        /// Atributo IdPT8
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdPT8 { get; set; }
    
    	/// <summary>
        /// Atributo SatffMemberName
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string SatffMemberName { get; set; }
    
    	/// <summary>
        /// Atributo SatffMemberIndexNumber
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string SatffMemberIndexNumber { get; set; }
    
    	/// <summary>
        /// Atributo TitleGrade
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string TitleGrade { get; set; }
    
    	/// <summary>
        /// Atributo Nationality
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Nationality { get; set; }
    
    	/// <summary>
        /// Atributo OfficeDuty
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string OfficeDuty { get; set; }
    
    	/// <summary>
        /// Atributo IdUnit
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdUnit { get; set; }
    
    	/// <summary>
        /// Atributo ExchangeRate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public double ExchangeRate { get; set; }
    
    	/// <summary>
        /// Atributo IdTravelAgency
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdTravelAgency { get; set; }
    
    	/// <summary>
        /// Atributo Purpose
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Purpose { get; set; }
    
    	/// <summary>
        /// Atributo SpecialInstruction
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string SpecialInstruction { get; set; }
    
    	/// <summary>
        /// Atributo RegisterAdded
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int RegisterAdded { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail1
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail1 { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion ItineraryInformation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<ItineraryInformation> ItineraryInformation { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion PT8
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual PT8 PT8 { get; set; }
    }
}
