//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class Services
    {
    
    	/// <summary>
        /// Atributo IdService
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdService { get; set; }
    
    	/// <summary>
        /// Atributo IdServiceType
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdServiceType { get; set; }
    
    	/// <summary>
        /// Atributo IdRequest
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdRequest { get; set; }
    
    	/// <summary>
        /// Atributo Context
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Context { get; set; }
    
    	/// <summary>
        /// Atributo NumberDays
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int NumberDays { get; set; }
    
    	/// <summary>
        /// Atributo HoursDay
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int HoursDay { get; set; }
    
    	/// <summary>
        /// Atributo Description
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Description { get; set; }
    
    	/// <summary>
        /// Atributo ServiceLocation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ServiceLocation { get; set; }
    
    	/// <summary>
        /// Atributo Specifications
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Specifications { get; set; }
    
    	/// <summary>
        /// Atributo ServiceResult
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ServiceResult { get; set; }
    
    	/// <summary>
        /// Atributo ExpectedDeliveryDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime ExpectedDeliveryDate { get; set; }
    
    	/// <summary>
        /// Atributo PriorDeliveryDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime PriorDeliveryDate { get; set; }
    
    	/// <summary>
        /// Atributo DeliveryPlace
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string DeliveryPlace { get; set; }
    
    	/// <summary>
        /// Atributo ContactPerson
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string ContactPerson { get; set; }
    
    	/// <summary>
        /// Atributo AlternativeDeliveryDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime AlternativeDeliveryDate { get; set; }
    
    	/// <summary>
        /// Atributo Observations
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Observations { get; set; }
    
    	/// <summary>
        /// Atributo Active
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Active { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Request
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Request Request { get; set; }
    }
}
