//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class Sessions
    {
    	/// <summary>
        /// Constructor Sessions
        /// </summary>
        public Sessions()
        {
            this.SessionComponentsByModule = new HashSet<SessionComponentsByModule>();
            this.SessionTargetMails = new HashSet<SessionTargetMails>();
        }
    
    
    	/// <summary>
        /// Atributo IdSession
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSession { get; set; }
    
    	/// <summary>
        /// Atributo GUID
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string GUID { get; set; }
    
    	/// <summary>
        /// Atributo SourceEmail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string SourceEmail { get; set; }
    
    	/// <summary>
        /// Atributo Subject
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Subject { get; set; }
    
    	/// <summary>
        /// Atributo BodyMail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string BodyMail { get; set; }
    
    	/// <summary>
        /// Atributo Send
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Send { get; set; }
    
    	/// <summary>
        /// Atributo IdProcessGroup
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdProcessGroup { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ParameterDetail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ParameterDetail ParameterDetail { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion SessionComponentsByModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<SessionComponentsByModule> SessionComponentsByModule { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion SessionTargetMails
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<SessionTargetMails> SessionTargetMails { get; set; }
    }
}
