//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class SessionTargetMails
    {
    	/// <summary>
        /// Constructor SessionTargetMails
        /// </summary>
        public SessionTargetMails()
        {
            this.SessionTargetMailProcessed = new HashSet<SessionTargetMailProcessed>();
        }
    
    
    	/// <summary>
        /// Atributo IdSessionTargetMail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSessionTargetMail { get; set; }
    
    	/// <summary>
        /// Atributo TargetMail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string TargetMail { get; set; }
    
    	/// <summary>
        /// Atributo IdSession
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSession { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion Sessions
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Sessions Sessions { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion SessionTargetMailProcessed
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<SessionTargetMailProcessed> SessionTargetMailProcessed { get; set; }
    }
}
