//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class SessionComponentsByModule
    {
    
    	/// <summary>
        /// Atributo IdSessionComponentByModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSessionComponentByModule { get; set; }
    
    	/// <summary>
        /// Atributo IdSession
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSession { get; set; }
    
    	/// <summary>
        /// Atributo IdComponentByModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdComponentByModule { get; set; }
    
    	/// <summary>
        /// Atributo IdInformation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdInformation { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion ComponentsByModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ComponentsByModule ComponentsByModule { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion Sessions
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Sessions Sessions { get; set; }
    }
}
