//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class SessionTargetMailProcessed
    {
    
    	/// <summary>
        /// Atributo IdSessionTargetMailProcessed
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSessionTargetMailProcessed { get; set; }
    
    	/// <summary>
        /// Atributo IdSessionTargetMail
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdSessionTargetMail { get; set; }
    
    	/// <summary>
        /// Atributo ProcessedDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime ProcessedDate { get; set; }
    
    	/// <summary>
        /// Atributo Processed
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public bool Processed { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion SessionTargetMails
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual SessionTargetMails SessionTargetMails { get; set; }
    }
}
