//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class StepsFlow
    {
    	/// <summary>
        /// Constructor StepsFlow
        /// </summary>
        public StepsFlow()
        {
            this.StepsFlowModule = new HashSet<StepsFlowModule>();
        }
    
    
    	/// <summary>
        /// Atributo IdStepFlow
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdStepFlow { get; set; }
    
    	/// <summary>
        /// Atributo Name
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Name { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion StepsFlowModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<StepsFlowModule> StepsFlowModule { get; set; }
    }
}
