//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class StepsFlowModule
    {
    	/// <summary>
        /// Constructor StepsFlowModule
        /// </summary>
        public StepsFlowModule()
        {
            this.StepsFlowModuleUser = new HashSet<StepsFlowModuleUser>();
        }
    
    
    	/// <summary>
        /// Atributo IdStepFlowModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdStepFlowModule { get; set; }
    
    	/// <summary>
        /// Atributo IdStepFlow
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdStepFlow { get; set; }
    
    	/// <summary>
        /// Atributo IdModule
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdModule { get; set; }
    
    	/// <summary>
        /// Atributo Sequence
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public byte Sequence { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion Modules
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual Modules Modules { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion StepsFlow
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual StepsFlow StepsFlow { get; set; }
    
    	/// <summary>
        /// Atributo de agregacion StepsFlowModuleUser
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<StepsFlowModuleUser> StepsFlowModuleUser { get; set; }
    }
}
