//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acnur.App.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// DTO TabCuenta
    /// </summary>
    [System.Runtime.Serialization.DataContract(IsReference=true)]
    [Serializable]
    public partial class WeeklyRequest
    {
    	/// <summary>
        /// Constructor WeeklyRequest
        /// </summary>
        public WeeklyRequest()
        {
            this.Weekly = new HashSet<Weekly>();
        }
    
    
    	/// <summary>
        /// Atributo IdWeeklyRequest
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdWeeklyRequest { get; set; }
    
    	/// <summary>
        /// Atributo IdRequestUnit
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public int IdRequestUnit { get; set; }
    
    	/// <summary>
        /// Atributo RequesterPerson
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string RequesterPerson { get; set; }
    
    	/// <summary>
        /// Atributo DutyStation
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string DutyStation { get; set; }
    
    	/// <summary>
        /// Atributo RequestDate
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime RequestDate { get; set; }
    
    	/// <summary>
        /// Atributo Responsible
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public string Responsible { get; set; }
    
    
    	/// <summary>
        /// Atributo de agregacion Weekly
        /// </summary>
    	[System.Runtime.Serialization.DataMember]
        public virtual ICollection<Weekly> Weekly { get; set; }
    }
}
